// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';
import {context} from '../models';

export function AddDeviceProfile(arg1:types.DeviceProfile):Promise<void>;

export function AddMotionProfile(arg1:types.MotionControllerProfile):Promise<void>;

export function ConnectDevice(arg1:string):Promise<void>;

export function ConnectMotion(arg1:string):Promise<void>;

export function DisconnectDevice(arg1:string):Promise<void>;

export function DisconnectMotion(arg1:string):Promise<void>;

export function ExportCalibrationPDF():Promise<void>;

export function GetCalibrationStatus():Promise<types.CalibrationTaskStatus>;

export function GetDataDir():Promise<string>;

export function GetDeviceProfiles():Promise<Array<types.DeviceProfile>>;

export function GetDeviceStatusAll():Promise<Array<types.DeviceStatus>>;

export function GetLatestData():Promise<Array<types.DataPayload>>;

export function GetMotionProfiles():Promise<Array<types.MotionControllerProfile>>;

export function GetMotionStatusAll():Promise<Array<types.MotionControllerStatus>>;

export function GetPublishRate():Promise<number>;

export function GetThreeHoleCalibInfo():Promise<Array<types.ThreeHoleCalibFileInfo>>;

export function GetThreeHoleTraversalStatus():Promise<types.ThreeHoleTraversalTaskStatus>;

export function IsRecording():Promise<boolean>;

export function IsThreeHoleCalibLoaded():Promise<boolean>;

export function ListRecordingFiles():Promise<Array<string>>;

export function LoadCSVFile():Promise<string>;

export function LoadThreeHoleCalibFiles(arg1:Array<string>):Promise<void>;

export function LoadThreeHoleConfig():Promise<types.ThreeHoleTraversalConfig>;

export function MotionDefinePosition(arg1:string,arg2:types.AxisName,arg3:number):Promise<void>;

export function MotionEmergencyStop(arg1:string):Promise<void>;

export function MotionGetLimitStatus(arg1:string,arg2:types.AxisName):Promise<types.LimitStatus>;

export function MotionHome(arg1:string,arg2:types.AxisName):Promise<void>;

export function MotionIsAxisMoving(arg1:string,arg2:types.AxisName):Promise<boolean>;

export function MotionIsMoving(arg1:string):Promise<boolean>;

export function MotionJog(arg1:string,arg2:types.AxisName,arg3:number,arg4:number):Promise<void>;

export function MotionMotorOff(arg1:string):Promise<void>;

export function MotionMoveBy(arg1:string,arg2:types.AxisName,arg3:number):Promise<void>;

export function MotionMoveTo(arg1:string,arg2:types.AxisName,arg3:number):Promise<void>;

export function MotionSetAcceleration(arg1:string,arg2:types.AxisName,arg3:number):Promise<void>;

export function MotionSetAxisDirection(arg1:string,arg2:types.AxisName,arg3:boolean):Promise<void>;

export function MotionSetDeceleration(arg1:string,arg2:types.AxisName,arg3:number):Promise<void>;

export function MotionStop(arg1:string,arg2:types.AxisName):Promise<void>;

export function MotionStopAll(arg1:string):Promise<void>;

export function MotionWaitForComplete(arg1:string,arg2:types.AxisName,arg3:number):Promise<void>;

export function PauseCalibration():Promise<void>;

export function PauseThreeHoleTraversal():Promise<void>;

export function ReadRecordingFile(arg1:string):Promise<string>;

export function RemoveDeviceProfile(arg1:string):Promise<void>;

export function RemoveMotionProfile(arg1:string):Promise<void>;

export function ResumeCalibration():Promise<void>;

export function ResumeThreeHoleTraversal():Promise<void>;

export function SaveThreeHoleConfig(arg1:types.ThreeHoleTraversalConfig):Promise<void>;

export function ScanDevices():Promise<Array<types.DiscoveredDevice>>;

export function SelectDataSavePath():Promise<string>;

export function SelectThreeHoleCalibFiles():Promise<Array<string>>;

export function SetDataSavePath(arg1:string):Promise<void>;

export function SetPublishRate(arg1:number):Promise<void>;

export function SetUnit(arg1:string,arg2:string):Promise<void>;

export function Shutdown(arg1:context.Context):Promise<void>;

export function StartAcquisition(arg1:string):Promise<void>;

export function StartAcquisitionAll():Promise<number>;

export function StartCalibration(arg1:types.CalibrationConfig):Promise<string>;

export function StartRecording():Promise<void>;

export function StartThreeHoleRealtimeMonitor(arg1:types.ThreeHoleTraversalConfig):Promise<void>;

export function StartThreeHoleTraversal(arg1:types.ThreeHoleTraversalConfig):Promise<string>;

export function Startup(arg1:context.Context):Promise<void>;

export function StopAcquisition(arg1:string):Promise<void>;

export function StopAcquisitionAll():Promise<void>;

export function StopCalibration():Promise<void>;

export function StopRecording():Promise<void>;

export function StopThreeHoleRealtimeMonitor():Promise<void>;

export function StopThreeHoleTraversal():Promise<void>;

export function UpdateDeviceProfile(arg1:types.DeviceProfile):Promise<void>;

export function UpdateMotionProfile(arg1:types.MotionControllerProfile):Promise<void>;
