// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConfigService 配置持久化服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "../types/models.js";

/**
 * LoadThreeHoleConfig 加载三孔移位测试配置（探针1）
 */
export function LoadThreeHoleProbe1Config(): $CancellablePromise<types$0.ThreeHoleTraversalConfig> {
    return $Call.ByID(623952165).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * LoadThreeHoleProbe2Config 加载三孔移位测试配置（探针2）
 */
export function LoadThreeHoleProbe2Config(): $CancellablePromise<types$0.ThreeHoleTraversalConfig> {
    return $Call.ByID(1847088276).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * SaveThreeHoleConfig 保存三孔移位测试配置（探针1）
 */
export function SaveThreeHoleProbe1Config(config: types$0.ThreeHoleTraversalConfig): $CancellablePromise<void> {
    return $Call.ByID(2924624826, config);
}

/**
 * SaveThreeHoleProbe2Config 保存三孔移位测试配置（探针2）
 */
export function SaveThreeHoleProbe2Config(config: types$0.ThreeHoleTraversalConfig): $CancellablePromise<void> {
    return $Call.ByID(4168982119, config);
}

/**
 * SelectDataSavePath 弹出文件夹选择对话框选择数据保存路径
 */
export function SelectDataSavePath(): $CancellablePromise<string> {
    return $Call.ByID(1892004354);
}

/**
 * SetDataSavePath 设置数据保存路径
 */
export function SetDataSavePath(path: string): $CancellablePromise<void> {
    return $Call.ByID(1023937586, path);
}

// Private type creation functions
const $$createType0 = types$0.ThreeHoleTraversalConfig.createFrom;
