// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DeviceService 设备管理服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "../types/models.js";

/**
 * AddDeviceProfile 添加设备配置
 */
export function AddDeviceProfile(profile: types$0.DeviceProfile): $CancellablePromise<void> {
    return $Call.ByID(3526646626, profile);
}

/**
 * ClearAllZeroOffsets 清除指定设备所有通道的零位偏移
 */
export function ClearAllZeroOffsets(id: string): $CancellablePromise<void> {
    return $Call.ByID(1903488134, id);
}

/**
 * ClearZeroOffset 清除指定通道的零位偏移
 */
export function ClearZeroOffset(id: string, channelIndex: number): $CancellablePromise<void> {
    return $Call.ByID(1200105536, id, channelIndex);
}

/**
 * ConnectDevice 连接设备
 */
export function ConnectDevice(id: string): $CancellablePromise<void> {
    return $Call.ByID(3087394048, id);
}

/**
 * DisconnectDevice 断开设备
 */
export function DisconnectDevice(id: string): $CancellablePromise<void> {
    return $Call.ByID(477021956, id);
}

/**
 * GetDeviceProfiles 获取所有设备配置
 */
export function GetDeviceProfiles(): $CancellablePromise<types$0.DeviceProfile[]> {
    return $Call.ByID(1199492848).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetDeviceStatusAll 获取所有设备状态
 */
export function GetDeviceStatusAll(): $CancellablePromise<types$0.DeviceStatus[]> {
    return $Call.ByID(3972007507).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetLatestData 获取最新数据快照
 */
export function GetLatestData(): $CancellablePromise<types$0.DataPayload[]> {
    return $Call.ByID(1379892519).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * ReadValveState 读取设备校准阀位（每次从设备读取，不持久化）
 */
export function ReadValveState(id: string): $CancellablePromise<types$0.ValveState> {
    return $Call.ByID(1625049843, id);
}

/**
 * RemoveDeviceProfile 删除设备配置
 */
export function RemoveDeviceProfile(id: string): $CancellablePromise<void> {
    return $Call.ByID(501050039, id);
}

/**
 * ScanDevices 扫描设备
 */
export function ScanDevices(): $CancellablePromise<types$0.DiscoveredDevice[]> {
    return $Call.ByID(1543375300).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * SetSingleThermocoupleType 设置单个通道的热电偶类型
 */
export function SetSingleThermocoupleType(id: string, channelIndex: number, tcType: string): $CancellablePromise<void> {
    return $Call.ByID(1716667371, id, channelIndex, tcType);
}

/**
 * SetThermocoupleType 设置设备热电偶类型（全通道批量设置）
 */
export function SetThermocoupleType(id: string, tcTypes: string): $CancellablePromise<void> {
    return $Call.ByID(842138495, id, tcTypes);
}

/**
 * SetUnit 设置设备压力单位
 */
export function SetUnit(id: string, unit: string): $CancellablePromise<void> {
    return $Call.ByID(1098549526, id, unit);
}

/**
 * SetValveState 切换设备校准阀位（采集进行中会被拒绝）
 */
export function SetValveState(id: string, state: types$0.ValveState): $CancellablePromise<void> {
    return $Call.ByID(3874892551, id, state);
}

/**
 * StartAcquisition 启动采集
 */
export function StartAcquisition(id: string): $CancellablePromise<void> {
    return $Call.ByID(138873339, id);
}

/**
 * StartAcquisitionAll 批量启动采集
 */
export function StartAcquisitionAll(): $CancellablePromise<number> {
    return $Call.ByID(3175906014);
}

/**
 * StopAcquisition 停止采集
 */
export function StopAcquisition(id: string): $CancellablePromise<void> {
    return $Call.ByID(2542133823, id);
}

/**
 * StopAcquisitionAll 批量停止采集
 */
export function StopAcquisitionAll(): $CancellablePromise<void> {
    return $Call.ByID(376629290);
}

/**
 * UpdateDeviceProfile 更新设备配置
 */
export function UpdateDeviceProfile(profile: types$0.DeviceProfile): $CancellablePromise<void> {
    return $Call.ByID(1151889656, profile);
}

/**
 * ZeroCalibrate 对指定设备的所有启用压力通道执行零位校准
 */
export function ZeroCalibrate(id: string): $CancellablePromise<void> {
    return $Call.ByID(963286367, id);
}

/**
 * ZeroCalibrateAll 对所有已连接且正在采集的压力采集设备批量执行零位校准
 */
export function ZeroCalibrateAll(): $CancellablePromise<types$0.ZeroCalibrateResult[]> {
    return $Call.ByID(1773570314).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * ZeroCalibrateChannel 对指定设备的单个通道执行零位校准
 */
export function ZeroCalibrateChannel(id: string, channelIndex: number): $CancellablePromise<void> {
    return $Call.ByID(2259552190, id, channelIndex);
}

// Private type creation functions
const $$createType0 = types$0.DeviceProfile.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = types$0.DeviceStatus.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = types$0.DataPayload.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = types$0.DiscoveredDevice.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = types$0.ZeroCalibrateResult.createFrom;
const $$createType9 = $Create.Array($$createType8);
