// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LogService 日志查看与配置服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "../types/models.js";

/**
 * ClearLogs 清空全部日志文件
 */
export function ClearLogs(): $CancellablePromise<void> {
    return $Call.ByID(434221696);
}

/**
 * ExportLogs 弹出保存对话框，将全部日志打包为 zip 导出
 */
export function ExportLogs(): $CancellablePromise<string> {
    return $Call.ByID(540572235);
}

/**
 * GetLogDir 获取日志目录路径
 */
export function GetLogDir(): $CancellablePromise<string> {
    return $Call.ByID(4189692227);
}

/**
 * GetLoggingConfig 获取当前日志配置
 */
export function GetLoggingConfig(): $CancellablePromise<types$0.LoggingConfig> {
    return $Call.ByID(1994204221).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ListLogFiles 列出日志文件（按修改时间从新到旧）
 */
export function ListLogFiles(): $CancellablePromise<types$0.LogFileInfo[]> {
    return $Call.ByID(1900046315).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * OpenLogDir 在资源管理器中打开日志目录
 */
export function OpenLogDir(): $CancellablePromise<void> {
    return $Call.ByID(898653871);
}

/**
 * ReadLogTail 读取日志文件末尾 maxLines 行（默认 200，上限 2000）
 */
export function ReadLogTail(fileName: string, maxLines: number): $CancellablePromise<string> {
    return $Call.ByID(1160476970, fileName, maxLines);
}

/**
 * SetLoggingConfig 保存并应用日志配置（级别/控制台/通信日志/保留与滚动策略）
 */
export function SetLoggingConfig(cfg: types$0.LoggingConfig): $CancellablePromise<void> {
    return $Call.ByID(304909481, cfg);
}

/**
 * WriteFrontendError 记录前端 JS 错误（Vue errorHandler / window.onerror 上报）
 */
export function WriteFrontendError(level: string, message: string, stack: string): $CancellablePromise<void> {
    return $Call.ByID(3847230521, level, message, stack);
}

// Private type creation functions
const $$createType0 = types$0.LoggingConfig.createFrom;
const $$createType1 = types$0.LogFileInfo.createFrom;
const $$createType2 = $Create.Array($$createType1);
