// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CalibrationService 五孔探针校准服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "../types/models.js";

/**
 * GetCalibrationStatus 获取校准状态
 */
export function GetCalibrationStatus(): $CancellablePromise<types$0.CalibrationTaskStatus> {
    return $Call.ByID(154910678).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * PauseCalibration 暂停校准
 */
export function PauseCalibration(): $CancellablePromise<void> {
    return $Call.ByID(2944807178);
}

/**
 * ResumeCalibration 恢复校准
 */
export function ResumeCalibration(): $CancellablePromise<void> {
    return $Call.ByID(2970526281);
}

/**
 * StartCalibration 启动校准
 */
export function StartCalibration(config: types$0.CalibrationConfig): $CancellablePromise<string> {
    return $Call.ByID(4164411828, config);
}

/**
 * StopCalibration 停止校准
 */
export function StopCalibration(): $CancellablePromise<void> {
    return $Call.ByID(3681541072);
}

// Private type creation functions
const $$createType0 = types$0.CalibrationTaskStatus.createFrom;
