// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DataService 数据录制与导出服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * ExportCalibrationPDF 导出校准PDF报告
 */
export function ExportCalibrationPDF(): $CancellablePromise<void> {
    return $Call.ByID(2122142302);
}

/**
 * GetDataDir 获取数据存储目录路径
 */
export function GetDataDir(): $CancellablePromise<string> {
    return $Call.ByID(2663910561);
}

/**
 * GetPublishRate 获取数据发布频率
 */
export function GetPublishRate(): $CancellablePromise<number> {
    return $Call.ByID(2130497651);
}

/**
 * IsRecording 是否正在录制
 */
export function IsRecording(): $CancellablePromise<boolean> {
    return $Call.ByID(2491832161);
}

/**
 * ListRecordingFiles 列出录制文件
 */
export function ListRecordingFiles(): $CancellablePromise<string[]> {
    return $Call.ByID(158376740).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * LoadCSVFile 加载CSV文件用于回放
 */
export function LoadCSVFile(): $CancellablePromise<string> {
    return $Call.ByID(3976563896);
}

/**
 * ReadRecordingFile 按文件名直接读取录制文件内容
 */
export function ReadRecordingFile(fileName: string): $CancellablePromise<string> {
    return $Call.ByID(2673517955, fileName);
}

/**
 * SetPublishRate 设置数据发布频率
 */
export function SetPublishRate(hz: number): $CancellablePromise<void> {
    return $Call.ByID(84509975, hz);
}

/**
 * StartRecording 开始录制
 */
export function StartRecording(): $CancellablePromise<void> {
    return $Call.ByID(2652829725);
}

/**
 * StopRecording 停止录制
 */
export function StopRecording(): $CancellablePromise<void> {
    return $Call.ByID(80639397);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
