// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DeviceService 设备管理服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "../types/models.js";

/**
 * AddDeviceProfile 添加设备配置
 */
export function AddDeviceProfile(profile: types$0.DeviceProfile): $CancellablePromise<void> {
    return $Call.ByID(3526646626, profile);
}

/**
 * ConnectDevice 连接设备
 */
export function ConnectDevice(id: string): $CancellablePromise<void> {
    return $Call.ByID(3087394048, id);
}

/**
 * DisconnectDevice 断开设备
 */
export function DisconnectDevice(id: string): $CancellablePromise<void> {
    return $Call.ByID(477021956, id);
}

/**
 * GetDeviceProfiles 获取所有设备配置
 */
export function GetDeviceProfiles(): $CancellablePromise<types$0.DeviceProfile[]> {
    return $Call.ByID(1199492848).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetDeviceStatusAll 获取所有设备状态
 */
export function GetDeviceStatusAll(): $CancellablePromise<types$0.DeviceStatus[]> {
    return $Call.ByID(3972007507).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetLatestData 获取最新数据快照
 */
export function GetLatestData(): $CancellablePromise<types$0.DataPayload[]> {
    return $Call.ByID(1379892519).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * RemoveDeviceProfile 删除设备配置
 */
export function RemoveDeviceProfile(id: string): $CancellablePromise<void> {
    return $Call.ByID(501050039, id);
}

/**
 * ScanDevices 扫描设备
 */
export function ScanDevices(): $CancellablePromise<types$0.DiscoveredDevice[]> {
    return $Call.ByID(1543375300).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * SetSingleThermocoupleType 设置单个通道的热电偶类型
 */
export function SetSingleThermocoupleType(id: string, channelIndex: number, tcType: string): $CancellablePromise<void> {
    return $Call.ByID(1716667371, id, channelIndex, tcType);
}

/**
 * SetThermocoupleType 设置设备热电偶类型（全通道批量设置）
 */
export function SetThermocoupleType(id: string, tcTypes: string): $CancellablePromise<void> {
    return $Call.ByID(842138495, id, tcTypes);
}

/**
 * SetUnit 设置设备压力单位
 */
export function SetUnit(id: string, unit: string): $CancellablePromise<void> {
    return $Call.ByID(1098549526, id, unit);
}

/**
 * StartAcquisition 启动采集
 */
export function StartAcquisition(id: string): $CancellablePromise<void> {
    return $Call.ByID(138873339, id);
}

/**
 * StartAcquisitionAll 批量启动采集
 */
export function StartAcquisitionAll(): $CancellablePromise<number> {
    return $Call.ByID(3175906014);
}

/**
 * StopAcquisition 停止采集
 */
export function StopAcquisition(id: string): $CancellablePromise<void> {
    return $Call.ByID(2542133823, id);
}

/**
 * StopAcquisitionAll 批量停止采集
 */
export function StopAcquisitionAll(): $CancellablePromise<void> {
    return $Call.ByID(376629290);
}

/**
 * UpdateDeviceProfile 更新设备配置
 */
export function UpdateDeviceProfile(profile: types$0.DeviceProfile): $CancellablePromise<void> {
    return $Call.ByID(1151889656, profile);
}

// Private type creation functions
const $$createType0 = types$0.DeviceProfile.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = types$0.DeviceStatus.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = types$0.DataPayload.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = types$0.DiscoveredDevice.createFrom;
const $$createType7 = $Create.Array($$createType6);
