// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FiveHoleService 五孔移位插值测试服务（Wails 绑定层，单实例管理 1-3 探针）
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "../types/models.js";

/**
 * GetFiveHoleCalibInfo 获取五孔校准文件信息
 */
export function GetFiveHoleCalibInfo(probeID: string): $CancellablePromise<types$0.FiveHoleCalibFileInfo[]> {
    return $Call.ByID(721521761, probeID).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetFiveHoleTraversalStatus 获取五孔移位测试状态
 */
export function GetFiveHoleTraversalStatus(): $CancellablePromise<types$0.FiveHoleTraversalTaskStatus> {
    return $Call.ByID(1949786406).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * IsFiveHoleCalibLoaded 五孔校准文件是否已加载
 */
export function IsFiveHoleCalibLoaded(probeID: string): $CancellablePromise<boolean> {
    return $Call.ByID(4189629024, probeID);
}

/**
 * IsFiveHoleRealtimeRecording 五孔实时数据是否正在录制
 */
export function IsFiveHoleRealtimeRecording(): $CancellablePromise<boolean> {
    return $Call.ByID(3912709406);
}

/**
 * LoadFiveHoleCalibFiles 加载五孔校准文件（按探针独立载入）
 */
export function LoadFiveHoleCalibFiles(probeID: string, filePaths: string[]): $CancellablePromise<void> {
    return $Call.ByID(3596891716, probeID, filePaths);
}

/**
 * LoadFiveHoleConfig 加载五孔移位测试配置
 */
export function LoadFiveHoleConfig(): $CancellablePromise<types$0.FiveHoleTraversalConfig> {
    return $Call.ByID(1299056688).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * OpenTestWindow 打开五孔测试窗口（单窗口，非三孔多窗口模式）
 */
export function OpenTestWindow(): $CancellablePromise<string> {
    return $Call.ByID(636139648);
}

/**
 * PauseFiveHoleTraversal 暂停五孔移位测试
 */
export function PauseFiveHoleTraversal(): $CancellablePromise<void> {
    return $Call.ByID(1799269314);
}

/**
 * ResumeFiveHoleTraversal 恢复五孔移位测试
 */
export function ResumeFiveHoleTraversal(): $CancellablePromise<void> {
    return $Call.ByID(678571705);
}

/**
 * SaveFiveHoleConfig 保存五孔移位测试配置（JSON 文件持久化）
 */
export function SaveFiveHoleConfig(config: types$0.FiveHoleTraversalConfig): $CancellablePromise<void> {
    return $Call.ByID(2569475457, config);
}

/**
 * SelectAndStartFiveHoleRealtimeRecording 弹出保存对话框选择路径后开始五孔实时数据录制
 */
export function SelectAndStartFiveHoleRealtimeRecording(): $CancellablePromise<string> {
    return $Call.ByID(3129538143);
}

/**
 * SelectFiveHoleCalibFiles 选择五孔校准文件（.prb）
 */
export function SelectFiveHoleCalibFiles(): $CancellablePromise<string[]> {
    return $Call.ByID(128678352).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * StartFiveHoleRealtimeMonitor 启动五孔实时数据监控
 */
export function StartFiveHoleRealtimeMonitor(config: types$0.FiveHoleTraversalConfig): $CancellablePromise<void> {
    return $Call.ByID(810398559, config);
}

/**
 * StartFiveHoleTraversal 启动五孔移位测试（统一控制 1-3 探针）
 */
export function StartFiveHoleTraversal(config: types$0.FiveHoleTraversalConfig): $CancellablePromise<string> {
    return $Call.ByID(1213142236, config);
}

/**
 * StopFiveHoleRealtimeMonitor 停止五孔实时数据监控
 */
export function StopFiveHoleRealtimeMonitor(): $CancellablePromise<void> {
    return $Call.ByID(764954083);
}

/**
 * StopFiveHoleRealtimeRecording 停止五孔实时数据录制
 */
export function StopFiveHoleRealtimeRecording(): $CancellablePromise<void> {
    return $Call.ByID(2457445902);
}

/**
 * StopFiveHoleTraversal 停止五孔移位测试（对所有涉及到的位移机构急停）
 */
export function StopFiveHoleTraversal(): $CancellablePromise<void> {
    return $Call.ByID(1757662112);
}

// Private type creation functions
const $$createType0 = types$0.FiveHoleCalibFileInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = types$0.FiveHoleTraversalTaskStatus.createFrom;
const $$createType3 = types$0.FiveHoleTraversalConfig.createFrom;
const $$createType4 = $Create.Array($Create.Any);
