// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MotionService 运动控制服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "../types/models.js";

/**
 * AddMotionProfile 添加运动控制器配置
 */
export function AddMotionProfile(profile: types$0.MotionControllerProfile): $CancellablePromise<void> {
    return $Call.ByID(543136086, profile);
}

/**
 * ConnectMotion 连接运动控制器
 */
export function ConnectMotion(id: string): $CancellablePromise<void> {
    return $Call.ByID(3629826920, id);
}

/**
 * DisconnectMotion 断开运动控制器
 */
export function DisconnectMotion(id: string): $CancellablePromise<void> {
    return $Call.ByID(2073089092, id);
}

/**
 * GetMotionProfiles 获取所有运动控制器配置
 */
export function GetMotionProfiles(): $CancellablePromise<types$0.MotionControllerProfile[]> {
    return $Call.ByID(1826367996).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetMotionStatusAll 获取所有运动控制器状态
 */
export function GetMotionStatusAll(): $CancellablePromise<types$0.MotionControllerStatus[]> {
    return $Call.ByID(1990798479).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * MotionDefinePosition 置位
 */
export function MotionDefinePosition(id: string, axis: types$0.AxisName, position: number): $CancellablePromise<void> {
    return $Call.ByID(3770140110, id, axis, position);
}

/**
 * MotionEmergencyStop 急停
 */
export function MotionEmergencyStop(id: string): $CancellablePromise<void> {
    return $Call.ByID(3374769591, id);
}

/**
 * MotionGetLimitStatus 查询轴限位状态
 */
export function MotionGetLimitStatus(id: string, axis: types$0.AxisName): $CancellablePromise<types$0.LimitStatus> {
    return $Call.ByID(1229675107, id, axis).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * MotionHome 回零
 */
export function MotionHome(id: string, axis: types$0.AxisName): $CancellablePromise<void> {
    return $Call.ByID(2061937545, id, axis);
}

/**
 * MotionIsAxisMoving 查询单轴是否在运动
 */
export function MotionIsAxisMoving(id: string, axis: types$0.AxisName): $CancellablePromise<boolean> {
    return $Call.ByID(1709461393, id, axis);
}

/**
 * MotionIsMoving 查询是否有轴在运动
 */
export function MotionIsMoving(id: string): $CancellablePromise<boolean> {
    return $Call.ByID(3758119280, id);
}

/**
 * MotionJog 点动
 */
export function MotionJog(id: string, axis: types$0.AxisName, direction: number, distance: number, speed: number): $CancellablePromise<void> {
    return $Call.ByID(2963648834, id, axis, direction, distance, speed);
}

/**
 * MotionMotorOff 关闭电机
 */
export function MotionMotorOff(id: string): $CancellablePromise<void> {
    return $Call.ByID(4161218916, id);
}

/**
 * MotionMoveBy 相对移动
 */
export function MotionMoveBy(id: string, axis: types$0.AxisName, delta: number): $CancellablePromise<void> {
    return $Call.ByID(4120496430, id, axis, delta);
}

/**
 * MotionMoveTo 绝对定位
 */
export function MotionMoveTo(id: string, axis: types$0.AxisName, position: number): $CancellablePromise<void> {
    return $Call.ByID(3883932478, id, axis, position);
}

/**
 * MotionSetAcceleration 设置加速度
 */
export function MotionSetAcceleration(id: string, axis: types$0.AxisName, accel: number): $CancellablePromise<void> {
    return $Call.ByID(2317015470, id, axis, accel);
}

/**
 * MotionSetAxisDirection 设置轴方向
 */
export function MotionSetAxisDirection(id: string, axis: types$0.AxisName, reverse: boolean): $CancellablePromise<void> {
    return $Call.ByID(3427942396, id, axis, reverse);
}

/**
 * MotionSetDeceleration 设置减速度
 */
export function MotionSetDeceleration(id: string, axis: types$0.AxisName, decel: number): $CancellablePromise<void> {
    return $Call.ByID(1769110625, id, axis, decel);
}

/**
 * MotionStop 停止
 */
export function MotionStop(id: string, axis: types$0.AxisName): $CancellablePromise<void> {
    return $Call.ByID(3346113806, id, axis);
}

/**
 * MotionStopAll 停止所有轴
 */
export function MotionStopAll(id: string): $CancellablePromise<void> {
    return $Call.ByID(795797085, id);
}

/**
 * MotionWaitForComplete 等待运动完成
 */
export function MotionWaitForComplete(id: string, axis: types$0.AxisName, timeoutMs: number): $CancellablePromise<void> {
    return $Call.ByID(2539582421, id, axis, timeoutMs);
}

/**
 * OpenMotionWindow 打开运动控制独立窗口（复用已有窗口，不重复创建）
 */
export function OpenMotionWindow(): $CancellablePromise<string> {
    return $Call.ByID(3529122618);
}

/**
 * RemoveMotionProfile 删除运动控制器配置
 */
export function RemoveMotionProfile(id: string): $CancellablePromise<void> {
    return $Call.ByID(1170766747, id);
}

/**
 * UpdateMotionProfile 更新运动控制器配置
 */
export function UpdateMotionProfile(profile: types$0.MotionControllerProfile): $CancellablePromise<void> {
    return $Call.ByID(2154264016, profile);
}

// Private type creation functions
const $$createType0 = types$0.MotionControllerProfile.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = types$0.MotionControllerStatus.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = types$0.LimitStatus.createFrom;
