// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ThreeHoleService 三孔移位插值测试服务（Wails 绑定层，支持多探针）
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "../types/models.js";

/**
 * GetThreeHoleCalibInfo 获取三孔校准文件信息
 */
export function GetThreeHoleCalibInfo(probeID: string): $CancellablePromise<types$0.ThreeHoleCalibFileInfo[]> {
    return $Call.ByID(2289589699, probeID).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetThreeHoleTraversalStatus 获取三孔移位测试状态
 */
export function GetThreeHoleTraversalStatus(probeID: string): $CancellablePromise<types$0.ThreeHoleTraversalTaskStatus> {
    return $Call.ByID(4108301036, probeID).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * IsThreeHoleCalibLoaded 三孔校准文件是否已加载
 */
export function IsThreeHoleCalibLoaded(probeID: string): $CancellablePromise<boolean> {
    return $Call.ByID(4254879142, probeID);
}

/**
 * LoadThreeHoleCalibFiles 加载三孔校准文件
 */
export function LoadThreeHoleCalibFiles(probeID: string, filePaths: string[]): $CancellablePromise<void> {
    return $Call.ByID(3075902634, probeID, filePaths);
}

/**
 * OpenTestWindow 打开探针测试窗口（复用已有窗口，不重复创建）
 */
export function OpenTestWindow(probeID: string): $CancellablePromise<string> {
    return $Call.ByID(4229824122, probeID);
}

/**
 * PauseThreeHoleTraversal 暂停三孔移位测试
 */
export function PauseThreeHoleTraversal(probeID: string): $CancellablePromise<void> {
    return $Call.ByID(2071267592, probeID);
}

/**
 * ResumeThreeHoleTraversal 恢复三孔移位测试
 */
export function ResumeThreeHoleTraversal(probeID: string): $CancellablePromise<void> {
    return $Call.ByID(4165064805, probeID);
}

/**
 * SelectThreeHoleCalibFiles 选择三孔校准文件
 */
export function SelectThreeHoleCalibFiles(): $CancellablePromise<string[]> {
    return $Call.ByID(2496301570).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * StartThreeHoleRealtimeMonitor 启动三孔实时数据监控
 */
export function StartThreeHoleRealtimeMonitor(probeID: string, config: types$0.ThreeHoleTraversalConfig): $CancellablePromise<void> {
    return $Call.ByID(4134459093, probeID, config);
}

/**
 * StartThreeHoleTraversal 启动三孔移位测试
 */
export function StartThreeHoleTraversal(probeID: string, config: types$0.ThreeHoleTraversalConfig): $CancellablePromise<string> {
    return $Call.ByID(3621092534, probeID, config);
}

/**
 * StopThreeHoleRealtimeMonitor 停止三孔实时数据监控
 */
export function StopThreeHoleRealtimeMonitor(probeID: string): $CancellablePromise<void> {
    return $Call.ByID(3094358397, probeID);
}

/**
 * StopThreeHoleTraversal 停止三孔移位测试
 */
export function StopThreeHoleTraversal(probeID: string): $CancellablePromise<void> {
    return $Call.ByID(1436089518, probeID);
}

// Private type creation functions
const $$createType0 = types$0.ThreeHoleCalibFileInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = types$0.ThreeHoleTraversalTaskStatus.createFrom;
const $$createType3 = $Create.Array($Create.Any);
