// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AxisConfig 轴配置
 */
export class AxisConfig {
    "name": AxisName;
    "enabled": boolean;
    "kind": AxisKind;
    "inverted": boolean;
    "stepAngleDeg": number;
    "microSteps": number;
    "lead": number;
    "gearRatio": number;
    "maxSpeed": number;
    "encoderScale": number;
    "encoderCompensation": EncoderCompensationConfig;

    /** Creates a new AxisConfig instance. */
    constructor($$source: Partial<AxisConfig> = {}) {
        if (!("name" in $$source)) {
            this["name"] = AxisName.$zero;
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("kind" in $$source)) {
            this["kind"] = AxisKind.$zero;
        }
        if (!("inverted" in $$source)) {
            this["inverted"] = false;
        }
        if (!("stepAngleDeg" in $$source)) {
            this["stepAngleDeg"] = 0;
        }
        if (!("microSteps" in $$source)) {
            this["microSteps"] = 0;
        }
        if (!("lead" in $$source)) {
            this["lead"] = 0;
        }
        if (!("gearRatio" in $$source)) {
            this["gearRatio"] = 0;
        }
        if (!("maxSpeed" in $$source)) {
            this["maxSpeed"] = 0;
        }
        if (!("encoderScale" in $$source)) {
            this["encoderScale"] = 0;
        }
        if (!("encoderCompensation" in $$source)) {
            this["encoderCompensation"] = (new EncoderCompensationConfig());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AxisConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): AxisConfig {
        const $$createField10_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("encoderCompensation" in $$parsedSource) {
            $$parsedSource["encoderCompensation"] = $$createField10_0($$parsedSource["encoderCompensation"]);
        }
        return new AxisConfig($$parsedSource as Partial<AxisConfig>);
    }
}

/**
 * AxisKind 轴类型
 */
export enum AxisKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    AxisKindLinear = "LINEAR",
    AxisKindRotary = "ROTARY",
};

/**
 * AxisName 逻辑轴名
 */
export enum AxisName {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    AxisX = "X",
    AxisY = "Y",
    AxisZ = "Z",
    AxisU = "U",
};

/**
 * AxisStatus 轴运行时状态
 */
export class AxisStatus {
    "name": AxisName;
    "position": number;
    "moving": boolean;
    "homed": boolean;
    "posLimit": boolean;
    "negLimit": boolean;
    "compensating": boolean;

    /** Creates a new AxisStatus instance. */
    constructor($$source: Partial<AxisStatus> = {}) {
        if (!("name" in $$source)) {
            this["name"] = AxisName.$zero;
        }
        if (!("position" in $$source)) {
            this["position"] = 0;
        }
        if (!("moving" in $$source)) {
            this["moving"] = false;
        }
        if (!("homed" in $$source)) {
            this["homed"] = false;
        }
        if (!("posLimit" in $$source)) {
            this["posLimit"] = false;
        }
        if (!("negLimit" in $$source)) {
            this["negLimit"] = false;
        }
        if (!("compensating" in $$source)) {
            this["compensating"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AxisStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): AxisStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AxisStatus($$parsedSource as Partial<AxisStatus>);
    }
}

/**
 * CalibrationConfig 校准配置
 */
export class CalibrationConfig {
    "type": CalibrationType;
    "deviceId": string;
    "controllerId": string;
    "probeChannels": ProbeChannelConfig[];
    "alphaAxis": AxisName;
    "betaAxis": AxisName;
    "points": CalibrationPoint[];
    "dwellTimeMs": number;
    "samplesPerPoint": number;
    "sphereTankGate": SphereTankGateConfig;

    /** Creates a new CalibrationConfig instance. */
    constructor($$source: Partial<CalibrationConfig> = {}) {
        if (!("type" in $$source)) {
            this["type"] = CalibrationType.$zero;
        }
        if (!("deviceId" in $$source)) {
            this["deviceId"] = "";
        }
        if (!("controllerId" in $$source)) {
            this["controllerId"] = "";
        }
        if (!("probeChannels" in $$source)) {
            this["probeChannels"] = [];
        }
        if (!("alphaAxis" in $$source)) {
            this["alphaAxis"] = AxisName.$zero;
        }
        if (!("betaAxis" in $$source)) {
            this["betaAxis"] = AxisName.$zero;
        }
        if (!("points" in $$source)) {
            this["points"] = [];
        }
        if (!("dwellTimeMs" in $$source)) {
            this["dwellTimeMs"] = 0;
        }
        if (!("samplesPerPoint" in $$source)) {
            this["samplesPerPoint"] = 0;
        }
        if (!("sphereTankGate" in $$source)) {
            this["sphereTankGate"] = (new SphereTankGateConfig());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CalibrationConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): CalibrationConfig {
        const $$createField3_0 = $$createType2;
        const $$createField6_0 = $$createType4;
        const $$createField9_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("probeChannels" in $$parsedSource) {
            $$parsedSource["probeChannels"] = $$createField3_0($$parsedSource["probeChannels"]);
        }
        if ("points" in $$parsedSource) {
            $$parsedSource["points"] = $$createField6_0($$parsedSource["points"]);
        }
        if ("sphereTankGate" in $$parsedSource) {
            $$parsedSource["sphereTankGate"] = $$createField9_0($$parsedSource["sphereTankGate"]);
        }
        return new CalibrationConfig($$parsedSource as Partial<CalibrationConfig>);
    }
}

/**
 * CalibrationDataPoint 校准数据点
 */
export class CalibrationDataPoint {
    "pointId": string;
    "alpha": number;
    "beta": number;
    "rawData": FiveHoleRawData;
    "coefficients": FiveHoleCoefficients;
    "sampleCount": number;
    "stdDev": number;

    /** Creates a new CalibrationDataPoint instance. */
    constructor($$source: Partial<CalibrationDataPoint> = {}) {
        if (!("pointId" in $$source)) {
            this["pointId"] = "";
        }
        if (!("alpha" in $$source)) {
            this["alpha"] = 0;
        }
        if (!("beta" in $$source)) {
            this["beta"] = 0;
        }
        if (!("rawData" in $$source)) {
            this["rawData"] = (new FiveHoleRawData());
        }
        if (!("coefficients" in $$source)) {
            this["coefficients"] = (new FiveHoleCoefficients());
        }
        if (!("sampleCount" in $$source)) {
            this["sampleCount"] = 0;
        }
        if (!("stdDev" in $$source)) {
            this["stdDev"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CalibrationDataPoint instance from a string or object.
     */
    static createFrom($$source: any = {}): CalibrationDataPoint {
        const $$createField3_0 = $$createType6;
        const $$createField4_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("rawData" in $$parsedSource) {
            $$parsedSource["rawData"] = $$createField3_0($$parsedSource["rawData"]);
        }
        if ("coefficients" in $$parsedSource) {
            $$parsedSource["coefficients"] = $$createField4_0($$parsedSource["coefficients"]);
        }
        return new CalibrationDataPoint($$parsedSource as Partial<CalibrationDataPoint>);
    }
}

/**
 * CalibrationPoint 校准点
 */
export class CalibrationPoint {
    "id": string;
    "alpha": number;
    "beta": number;

    /** Creates a new CalibrationPoint instance. */
    constructor($$source: Partial<CalibrationPoint> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("alpha" in $$source)) {
            this["alpha"] = 0;
        }
        if (!("beta" in $$source)) {
            this["beta"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CalibrationPoint instance from a string or object.
     */
    static createFrom($$source: any = {}): CalibrationPoint {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CalibrationPoint($$parsedSource as Partial<CalibrationPoint>);
    }
}

/**
 * CalibrationStatus 校准状态
 */
export enum CalibrationStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    CalibStatusIdle = "idle",
    CalibStatusConfiguring = "configuring",
    CalibStatusRunning = "running",
    CalibStatusPaused = "paused",
    CalibStatusCompleted = "completed",
    CalibStatusError = "error",
};

/**
 * CalibrationTaskStatus 校准任务状态
 */
export class CalibrationTaskStatus {
    "taskId": string;
    "status": CalibrationStatus;
    "totalPoints": number;
    "completedPoints": number;
    "progress": number;
    "currentPoint"?: CalibrationPoint | null;
    "dataPoints": CalibrationDataPoint[];
    "lastError"?: string;

    /** Creates a new CalibrationTaskStatus instance. */
    constructor($$source: Partial<CalibrationTaskStatus> = {}) {
        if (!("taskId" in $$source)) {
            this["taskId"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = CalibrationStatus.$zero;
        }
        if (!("totalPoints" in $$source)) {
            this["totalPoints"] = 0;
        }
        if (!("completedPoints" in $$source)) {
            this["completedPoints"] = 0;
        }
        if (!("progress" in $$source)) {
            this["progress"] = 0;
        }
        if (!("dataPoints" in $$source)) {
            this["dataPoints"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CalibrationTaskStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): CalibrationTaskStatus {
        const $$createField5_0 = $$createType8;
        const $$createField6_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("currentPoint" in $$parsedSource) {
            $$parsedSource["currentPoint"] = $$createField5_0($$parsedSource["currentPoint"]);
        }
        if ("dataPoints" in $$parsedSource) {
            $$parsedSource["dataPoints"] = $$createField6_0($$parsedSource["dataPoints"]);
        }
        return new CalibrationTaskStatus($$parsedSource as Partial<CalibrationTaskStatus>);
    }
}

/**
 * CalibrationType 校准类型
 */
export enum CalibrationType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    CalibrationTypeFiveHole = "five-hole",
};

/**
 * ChannelConfig 通道配置
 */
export class ChannelConfig {
    "index": number;
    "name": string;
    "enabled": boolean;
    "unit": string;
    "precision": number;
    "rangeMin": number;
    "rangeMax": number;

    /**
     * 热电偶类型（K/J/T/E/N/S/R/B/C/WRE325/WRE526/WRE520），仅 YX-DAQ-T
     */
    "thermocoupleType"?: string;

    /** Creates a new ChannelConfig instance. */
    constructor($$source: Partial<ChannelConfig> = {}) {
        if (!("index" in $$source)) {
            this["index"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("unit" in $$source)) {
            this["unit"] = "";
        }
        if (!("precision" in $$source)) {
            this["precision"] = 0;
        }
        if (!("rangeMin" in $$source)) {
            this["rangeMin"] = 0;
        }
        if (!("rangeMax" in $$source)) {
            this["rangeMax"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChannelConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): ChannelConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ChannelConfig($$parsedSource as Partial<ChannelConfig>);
    }
}

/**
 * ConnectionStatus 连接状态
 */
export enum ConnectionStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StatusDisconnected = "Disconnected",
    StatusConnecting = "Connecting",
    StatusConnected = "Connected",
    StatusError = "Error",
};

/**
 * DataPayload 数据帧
 */
export class DataPayload {
    "deviceId": string;
    "timestamp": number;
    "channels": number[];
    "channelIndices": number[];
    "channelUnits": string[];

    /** Creates a new DataPayload instance. */
    constructor($$source: Partial<DataPayload> = {}) {
        if (!("deviceId" in $$source)) {
            this["deviceId"] = "";
        }
        if (!("timestamp" in $$source)) {
            this["timestamp"] = 0;
        }
        if (!("channels" in $$source)) {
            this["channels"] = [];
        }
        if (!("channelIndices" in $$source)) {
            this["channelIndices"] = [];
        }
        if (!("channelUnits" in $$source)) {
            this["channelUnits"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DataPayload instance from a string or object.
     */
    static createFrom($$source: any = {}): DataPayload {
        const $$createField2_0 = $$createType11;
        const $$createField3_0 = $$createType12;
        const $$createField4_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("channels" in $$parsedSource) {
            $$parsedSource["channels"] = $$createField2_0($$parsedSource["channels"]);
        }
        if ("channelIndices" in $$parsedSource) {
            $$parsedSource["channelIndices"] = $$createField3_0($$parsedSource["channelIndices"]);
        }
        if ("channelUnits" in $$parsedSource) {
            $$parsedSource["channelUnits"] = $$createField4_0($$parsedSource["channelUnits"]);
        }
        return new DataPayload($$parsedSource as Partial<DataPayload>);
    }
}

/**
 * DeviceProfile 设备完整配置
 */
export class DeviceProfile {
    "id": string;
    "name": string;
    "type": DeviceType;
    "host": string;
    "port": number;
    "streamId": number;

    /**
     * 采集周期(毫秒)，0表示使用默认50ms
     */
    "periodMs": number;

    /**
     * 是否自动连接
     */
    "autoConnect": boolean;
    "channels": ChannelConfig[];

    /** Creates a new DeviceProfile instance. */
    constructor($$source: Partial<DeviceProfile> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = DeviceType.$zero;
        }
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("streamId" in $$source)) {
            this["streamId"] = 0;
        }
        if (!("periodMs" in $$source)) {
            this["periodMs"] = 0;
        }
        if (!("autoConnect" in $$source)) {
            this["autoConnect"] = false;
        }
        if (!("channels" in $$source)) {
            this["channels"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeviceProfile instance from a string or object.
     */
    static createFrom($$source: any = {}): DeviceProfile {
        const $$createField8_0 = $$createType15;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("channels" in $$parsedSource) {
            $$parsedSource["channels"] = $$createField8_0($$parsedSource["channels"]);
        }
        return new DeviceProfile($$parsedSource as Partial<DeviceProfile>);
    }
}

/**
 * DeviceStatus 设备状态摘要
 */
export class DeviceStatus {
    "id": string;
    "name": string;
    "type": DeviceType;
    "status": ConnectionStatus;
    "acquiring": boolean;
    "lastError": string;

    /** Creates a new DeviceStatus instance. */
    constructor($$source: Partial<DeviceStatus> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = DeviceType.$zero;
        }
        if (!("status" in $$source)) {
            this["status"] = ConnectionStatus.$zero;
        }
        if (!("acquiring" in $$source)) {
            this["acquiring"] = false;
        }
        if (!("lastError" in $$source)) {
            this["lastError"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeviceStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): DeviceStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DeviceStatus($$parsedSource as Partial<DeviceStatus>);
    }
}

/**
 * DeviceType 设备类型标识
 */
export enum DeviceType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    DeviceTypeSimulated = "SIMULATED",
    DeviceTypeXYDAQ8 = "XY-DAQ8",
    DeviceTypeXYDAQ16 = "XY-DAQ16",
    DeviceTypeYXDAQT = "YX-DAQ-T",
};

/**
 * DiscoveredDevice UDP扫描发现的设备
 */
export class DiscoveredDevice {
    "ip": string;
    "mac": string;
    "sn": string;
    "firmware": string;
    "port": number;
    "mask": string;
    "gateway": string;

    /** Creates a new DiscoveredDevice instance. */
    constructor($$source: Partial<DiscoveredDevice> = {}) {
        if (!("ip" in $$source)) {
            this["ip"] = "";
        }
        if (!("mac" in $$source)) {
            this["mac"] = "";
        }
        if (!("sn" in $$source)) {
            this["sn"] = "";
        }
        if (!("firmware" in $$source)) {
            this["firmware"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("mask" in $$source)) {
            this["mask"] = "";
        }
        if (!("gateway" in $$source)) {
            this["gateway"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DiscoveredDevice instance from a string or object.
     */
    static createFrom($$source: any = {}): DiscoveredDevice {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DiscoveredDevice($$parsedSource as Partial<DiscoveredDevice>);
    }
}

/**
 * EncoderCompensationConfig 编码器补偿配置
 */
export class EncoderCompensationConfig {
    "enabled": boolean;
    "tolerance": number;
    "maxCycles": number;
    "settleMs": number;
    "minStep": number;
    "timeoutMs": number;

    /** Creates a new EncoderCompensationConfig instance. */
    constructor($$source: Partial<EncoderCompensationConfig> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("tolerance" in $$source)) {
            this["tolerance"] = 0;
        }
        if (!("maxCycles" in $$source)) {
            this["maxCycles"] = 0;
        }
        if (!("settleMs" in $$source)) {
            this["settleMs"] = 0;
        }
        if (!("minStep" in $$source)) {
            this["minStep"] = 0;
        }
        if (!("timeoutMs" in $$source)) {
            this["timeoutMs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EncoderCompensationConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): EncoderCompensationConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EncoderCompensationConfig($$parsedSource as Partial<EncoderCompensationConfig>);
    }
}

/**
 * FiveHoleCalibFileInfo 五孔校准文件信息
 */
export class FiveHoleCalibFileInfo {
    "filePath": string;
    "fileName": string;

    /**
     * 校准马赫数
     */
    "cMa": number;

    /** Creates a new FiveHoleCalibFileInfo instance. */
    constructor($$source: Partial<FiveHoleCalibFileInfo> = {}) {
        if (!("filePath" in $$source)) {
            this["filePath"] = "";
        }
        if (!("fileName" in $$source)) {
            this["fileName"] = "";
        }
        if (!("cMa" in $$source)) {
            this["cMa"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FiveHoleCalibFileInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): FiveHoleCalibFileInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FiveHoleCalibFileInfo($$parsedSource as Partial<FiveHoleCalibFileInfo>);
    }
}

/**
 * FiveHoleChannelRole 五孔探针通道语义角色
 */
export enum FiveHoleChannelRole {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * 1号孔压力
     */
    Role5H_P1 = "fiveHole.p1",

    /**
     * 2号孔压力（中心孔）
     */
    Role5H_P2 = "fiveHole.p2",

    /**
     * 3号孔压力
     */
    Role5H_P3 = "fiveHole.p3",

    /**
     * 4号孔压力
     */
    Role5H_P4 = "fiveHole.p4",

    /**
     * 5号孔压力
     */
    Role5H_P5 = "fiveHole.p5",

    /**
     * 大气压（全局共享）
     */
    Role5H_PAtm = "fiveHole.pAtm",

    /**
     * 大气温度（全局共享）
     */
    Role5H_TAtm = "fiveHole.tAtm",
};

/**
 * FiveHoleCoefficients 五孔系数
 */
export class FiveHoleCoefficients {
    "Kalpha": number;
    "Kbeta": number;
    "CPT": number;
    "CPS": number;

    /** Creates a new FiveHoleCoefficients instance. */
    constructor($$source: Partial<FiveHoleCoefficients> = {}) {
        if (!("Kalpha" in $$source)) {
            this["Kalpha"] = 0;
        }
        if (!("Kbeta" in $$source)) {
            this["Kbeta"] = 0;
        }
        if (!("CPT" in $$source)) {
            this["CPT"] = 0;
        }
        if (!("CPS" in $$source)) {
            this["CPS"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FiveHoleCoefficients instance from a string or object.
     */
    static createFrom($$source: any = {}): FiveHoleCoefficients {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FiveHoleCoefficients($$parsedSource as Partial<FiveHoleCoefficients>);
    }
}

/**
 * FiveHoleInterpolationResult 五孔插值结果
 */
export class FiveHoleInterpolationResult {
    /**
     * 总压（表压 Pa）
     */
    "ptProbe": number;

    /**
     * 静压（表压 Pa）
     */
    "psProbe": number;

    /**
     * 马赫数
     */
    "machProbe": number;

    /**
     * 攻角（度）
     */
    "alphaProbe": number;

    /**
     * 侧滑角（度）
     */
    "betaProbe": number;

    /**
     * 速度（m/s）
     */
    "velocityProbe": number;

    /**
     * 迭代收敛次数
     */
    "iterationCount": number;

    /**
     * 迭代是否收敛
     */
    "converged": boolean;

    /**
     * 结果是否有效
     */
    "valid": boolean;

    /**
     * 无效/警告原因描述
     */
    "errorMsg"?: string;

    /** Creates a new FiveHoleInterpolationResult instance. */
    constructor($$source: Partial<FiveHoleInterpolationResult> = {}) {
        if (!("ptProbe" in $$source)) {
            this["ptProbe"] = 0;
        }
        if (!("psProbe" in $$source)) {
            this["psProbe"] = 0;
        }
        if (!("machProbe" in $$source)) {
            this["machProbe"] = 0;
        }
        if (!("alphaProbe" in $$source)) {
            this["alphaProbe"] = 0;
        }
        if (!("betaProbe" in $$source)) {
            this["betaProbe"] = 0;
        }
        if (!("velocityProbe" in $$source)) {
            this["velocityProbe"] = 0;
        }
        if (!("iterationCount" in $$source)) {
            this["iterationCount"] = 0;
        }
        if (!("converged" in $$source)) {
            this["converged"] = false;
        }
        if (!("valid" in $$source)) {
            this["valid"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FiveHoleInterpolationResult instance from a string or object.
     */
    static createFrom($$source: any = {}): FiveHoleInterpolationResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FiveHoleInterpolationResult($$parsedSource as Partial<FiveHoleInterpolationResult>);
    }
}

/**
 * FiveHoleMotionAxisMapping 五孔运动轴映射（每轴独立选位移机构）
 * 与三孔 MotionAxisMapping 区别：含 ControllerID，支持每轴独立位移机构
 */
export class FiveHoleMotionAxisMapping {
    /**
     * 位移机构ID
     */
    "controllerId": string;

    /**
     * 轴名（X/Y/Z/U）
     */
    "axis": AxisName;

    /** Creates a new FiveHoleMotionAxisMapping instance. */
    constructor($$source: Partial<FiveHoleMotionAxisMapping> = {}) {
        if (!("controllerId" in $$source)) {
            this["controllerId"] = "";
        }
        if (!("axis" in $$source)) {
            this["axis"] = AxisName.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FiveHoleMotionAxisMapping instance from a string or object.
     */
    static createFrom($$source: any = {}): FiveHoleMotionAxisMapping {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FiveHoleMotionAxisMapping($$parsedSource as Partial<FiveHoleMotionAxisMapping>);
    }
}

/**
 * FiveHoleProbeChannelConfig 五孔探针通道配置（每通道独立选采集设备）
 */
export class FiveHoleProbeChannelConfig {
    "name": string;
    "role": FiveHoleChannelRole;

    /**
     * 每通道独立选采集设备
     */
    "deviceId": string;
    "channel": number;
    "enabled": boolean;

    /** Creates a new FiveHoleProbeChannelConfig instance. */
    constructor($$source: Partial<FiveHoleProbeChannelConfig> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("role" in $$source)) {
            this["role"] = FiveHoleChannelRole.$zero;
        }
        if (!("deviceId" in $$source)) {
            this["deviceId"] = "";
        }
        if (!("channel" in $$source)) {
            this["channel"] = 0;
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FiveHoleProbeChannelConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): FiveHoleProbeChannelConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FiveHoleProbeChannelConfig($$parsedSource as Partial<FiveHoleProbeChannelConfig>);
    }
}

/**
 * FiveHoleProbeConfig 单根五孔探针配置
 */
export class FiveHoleProbeConfig {
    /**
     * probe1/probe2/probe3
     */
    "probeId": string;

    /**
     * 是否启用（配几根跑几根）
     */
    "enabled": boolean;

    /**
     * P1-P5 各自数据源
     */
    "probeChannels": FiveHoleProbeChannelConfig[];

    /**
     * α 轴：位移机构 + 轴号
     */
    "motionAlpha": FiveHoleMotionAxisMapping;

    /**
     * β 轴：位移机构 + 轴号
     */
    "motionBeta": FiveHoleMotionAxisMapping;

    /**
     * .prb 校准文件（每探针独立载入）
     */
    "calibFiles": FiveHoleCalibFileInfo[];

    /** Creates a new FiveHoleProbeConfig instance. */
    constructor($$source: Partial<FiveHoleProbeConfig> = {}) {
        if (!("probeId" in $$source)) {
            this["probeId"] = "";
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("probeChannels" in $$source)) {
            this["probeChannels"] = [];
        }
        if (!("motionAlpha" in $$source)) {
            this["motionAlpha"] = (new FiveHoleMotionAxisMapping());
        }
        if (!("motionBeta" in $$source)) {
            this["motionBeta"] = (new FiveHoleMotionAxisMapping());
        }
        if (!("calibFiles" in $$source)) {
            this["calibFiles"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FiveHoleProbeConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): FiveHoleProbeConfig {
        const $$createField2_0 = $$createType17;
        const $$createField3_0 = $$createType18;
        const $$createField4_0 = $$createType18;
        const $$createField5_0 = $$createType20;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("probeChannels" in $$parsedSource) {
            $$parsedSource["probeChannels"] = $$createField2_0($$parsedSource["probeChannels"]);
        }
        if ("motionAlpha" in $$parsedSource) {
            $$parsedSource["motionAlpha"] = $$createField3_0($$parsedSource["motionAlpha"]);
        }
        if ("motionBeta" in $$parsedSource) {
            $$parsedSource["motionBeta"] = $$createField4_0($$parsedSource["motionBeta"]);
        }
        if ("calibFiles" in $$parsedSource) {
            $$parsedSource["calibFiles"] = $$createField5_0($$parsedSource["calibFiles"]);
        }
        return new FiveHoleProbeConfig($$parsedSource as Partial<FiveHoleProbeConfig>);
    }
}

/**
 * FiveHoleProbeStatus 单根探针实时状态
 */
export class FiveHoleProbeStatus {
    "probeId": string;

    /**
     * moving/waiting/acquiring/completed
     */
    "phase": string;
    "currentX": number;
    "currentY": number;
    "rawData"?: FiveHoleRawData | null;
    "interpResult"?: FiveHoleInterpolationResult | null;

    /** Creates a new FiveHoleProbeStatus instance. */
    constructor($$source: Partial<FiveHoleProbeStatus> = {}) {
        if (!("probeId" in $$source)) {
            this["probeId"] = "";
        }
        if (!("phase" in $$source)) {
            this["phase"] = "";
        }
        if (!("currentX" in $$source)) {
            this["currentX"] = 0;
        }
        if (!("currentY" in $$source)) {
            this["currentY"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FiveHoleProbeStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): FiveHoleProbeStatus {
        const $$createField4_0 = $$createType21;
        const $$createField5_0 = $$createType23;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("rawData" in $$parsedSource) {
            $$parsedSource["rawData"] = $$createField4_0($$parsedSource["rawData"]);
        }
        if ("interpResult" in $$parsedSource) {
            $$parsedSource["interpResult"] = $$createField5_0($$parsedSource["interpResult"]);
        }
        return new FiveHoleProbeStatus($$parsedSource as Partial<FiveHoleProbeStatus>);
    }
}

/**
 * FiveHoleRawData 五孔原始数据
 */
export class FiveHoleRawData {
    "p1": number;
    "p2": number;
    "p3": number;
    "p4": number;
    "p5": number;
    "pAtm": number;
    "tAtm": number;
    "pTotal"?: number | null;

    /** Creates a new FiveHoleRawData instance. */
    constructor($$source: Partial<FiveHoleRawData> = {}) {
        if (!("p1" in $$source)) {
            this["p1"] = 0;
        }
        if (!("p2" in $$source)) {
            this["p2"] = 0;
        }
        if (!("p3" in $$source)) {
            this["p3"] = 0;
        }
        if (!("p4" in $$source)) {
            this["p4"] = 0;
        }
        if (!("p5" in $$source)) {
            this["p5"] = 0;
        }
        if (!("pAtm" in $$source)) {
            this["pAtm"] = 0;
        }
        if (!("tAtm" in $$source)) {
            this["tAtm"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FiveHoleRawData instance from a string or object.
     */
    static createFrom($$source: any = {}): FiveHoleRawData {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FiveHoleRawData($$parsedSource as Partial<FiveHoleRawData>);
    }
}

/**
 * FiveHoleTraversalConfig 五孔移位测试配置（全局配置，含 1-3 探针）
 */
export class FiveHoleTraversalConfig {
    "name": string;

    /**
     * 布点（复用三孔 TraversalLayout）
     */
    "layout": TraversalLayout;

    /**
     * 驻留时间（三根共用）
     */
    "dwellTimeMs": number;

    /**
     * 采样次数（三根共用）
     */
    "samplesPerPoint": number;

    /**
     * 采样间隔（三根共用）
     */
    "sampleIntervalMs": number;

    /**
     * 运动等待超时（三根共用）
     */
    "motionTimeoutMs": number;

    /**
     * PAtm/TAtm 全局共享数据源（三根共用）
     */
    "pAtmDeviceId": string;
    "pAtmChannel": number;
    "tAtmDeviceId": string;
    "tAtmChannel": number;

    /**
     * 1-3 根探针（配几根跑几根）
     */
    "probes": FiveHoleProbeConfig[];
    "savePath": string;
    "saveFileName": string;

    /** Creates a new FiveHoleTraversalConfig instance. */
    constructor($$source: Partial<FiveHoleTraversalConfig> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("layout" in $$source)) {
            this["layout"] = (new TraversalLayout());
        }
        if (!("dwellTimeMs" in $$source)) {
            this["dwellTimeMs"] = 0;
        }
        if (!("samplesPerPoint" in $$source)) {
            this["samplesPerPoint"] = 0;
        }
        if (!("sampleIntervalMs" in $$source)) {
            this["sampleIntervalMs"] = 0;
        }
        if (!("motionTimeoutMs" in $$source)) {
            this["motionTimeoutMs"] = 0;
        }
        if (!("pAtmDeviceId" in $$source)) {
            this["pAtmDeviceId"] = "";
        }
        if (!("pAtmChannel" in $$source)) {
            this["pAtmChannel"] = 0;
        }
        if (!("tAtmDeviceId" in $$source)) {
            this["tAtmDeviceId"] = "";
        }
        if (!("tAtmChannel" in $$source)) {
            this["tAtmChannel"] = 0;
        }
        if (!("probes" in $$source)) {
            this["probes"] = [];
        }
        if (!("savePath" in $$source)) {
            this["savePath"] = "";
        }
        if (!("saveFileName" in $$source)) {
            this["saveFileName"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FiveHoleTraversalConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): FiveHoleTraversalConfig {
        const $$createField1_0 = $$createType24;
        const $$createField10_0 = $$createType26;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("layout" in $$parsedSource) {
            $$parsedSource["layout"] = $$createField1_0($$parsedSource["layout"]);
        }
        if ("probes" in $$parsedSource) {
            $$parsedSource["probes"] = $$createField10_0($$parsedSource["probes"]);
        }
        return new FiveHoleTraversalConfig($$parsedSource as Partial<FiveHoleTraversalConfig>);
    }
}

/**
 * FiveHoleTraversalTaskStatus 五孔测试任务状态
 */
export class FiveHoleTraversalTaskStatus {
    "taskId": string;

    /**
     * 统一状态
     */
    "status": TraversalTestStatus;
    "totalPoints": number;

    /**
     * 统一进度（等最慢探针）
     */
    "completedPoints": number;
    "progress": number;
    "currentPoint"?: TraversalPoint | null;

    /**
     * 每探针独立 phase/坐标（统一进度 + 各探针 phase 指示）
     */
    "probeStatuses": FiveHoleProbeStatus[];
    "lastError"?: string;

    /** Creates a new FiveHoleTraversalTaskStatus instance. */
    constructor($$source: Partial<FiveHoleTraversalTaskStatus> = {}) {
        if (!("taskId" in $$source)) {
            this["taskId"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = TraversalTestStatus.$zero;
        }
        if (!("totalPoints" in $$source)) {
            this["totalPoints"] = 0;
        }
        if (!("completedPoints" in $$source)) {
            this["completedPoints"] = 0;
        }
        if (!("progress" in $$source)) {
            this["progress"] = 0;
        }
        if (!("probeStatuses" in $$source)) {
            this["probeStatuses"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FiveHoleTraversalTaskStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): FiveHoleTraversalTaskStatus {
        const $$createField5_0 = $$createType28;
        const $$createField6_0 = $$createType30;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("currentPoint" in $$parsedSource) {
            $$parsedSource["currentPoint"] = $$createField5_0($$parsedSource["currentPoint"]);
        }
        if ("probeStatuses" in $$parsedSource) {
            $$parsedSource["probeStatuses"] = $$createField6_0($$parsedSource["probeStatuses"]);
        }
        return new FiveHoleTraversalTaskStatus($$parsedSource as Partial<FiveHoleTraversalTaskStatus>);
    }
}

/**
 * LimitStatus 限位状态
 */
export class LimitStatus {
    "posLimit": boolean;
    "negLimit": boolean;

    /** Creates a new LimitStatus instance. */
    constructor($$source: Partial<LimitStatus> = {}) {
        if (!("posLimit" in $$source)) {
            this["posLimit"] = false;
        }
        if (!("negLimit" in $$source)) {
            this["negLimit"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LimitStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): LimitStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LimitStatus($$parsedSource as Partial<LimitStatus>);
    }
}

/**
 * LineLayout 直线布点配置
 */
export class LineLayout {
    "startX": number;
    "startY": number;
    "endX": number;
    "endY": number;
    "xSteps": StepSegment[];
    "ySteps": StepSegment[];

    /** Creates a new LineLayout instance. */
    constructor($$source: Partial<LineLayout> = {}) {
        if (!("startX" in $$source)) {
            this["startX"] = 0;
        }
        if (!("startY" in $$source)) {
            this["startY"] = 0;
        }
        if (!("endX" in $$source)) {
            this["endX"] = 0;
        }
        if (!("endY" in $$source)) {
            this["endY"] = 0;
        }
        if (!("xSteps" in $$source)) {
            this["xSteps"] = [];
        }
        if (!("ySteps" in $$source)) {
            this["ySteps"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LineLayout instance from a string or object.
     */
    static createFrom($$source: any = {}): LineLayout {
        const $$createField4_0 = $$createType32;
        const $$createField5_0 = $$createType32;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("xSteps" in $$parsedSource) {
            $$parsedSource["xSteps"] = $$createField4_0($$parsedSource["xSteps"]);
        }
        if ("ySteps" in $$parsedSource) {
            $$parsedSource["ySteps"] = $$createField5_0($$parsedSource["ySteps"]);
        }
        return new LineLayout($$parsedSource as Partial<LineLayout>);
    }
}

/**
 * MotionAxisMapping 运动轴映射
 */
export class MotionAxisMapping {
    "axis": AxisName;

    /** Creates a new MotionAxisMapping instance. */
    constructor($$source: Partial<MotionAxisMapping> = {}) {
        if (!("axis" in $$source)) {
            this["axis"] = AxisName.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MotionAxisMapping instance from a string or object.
     */
    static createFrom($$source: any = {}): MotionAxisMapping {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MotionAxisMapping($$parsedSource as Partial<MotionAxisMapping>);
    }
}

/**
 * MotionControllerProfile 运动控制器配置
 */
export class MotionControllerProfile {
    "id": string;
    "name": string;
    "type": MotionControllerType;
    "address": string;
    "port": number;
    "timeoutMs": number;
    "axes": AxisConfig[];

    /** Creates a new MotionControllerProfile instance. */
    constructor($$source: Partial<MotionControllerProfile> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = MotionControllerType.$zero;
        }
        if (!("address" in $$source)) {
            this["address"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("timeoutMs" in $$source)) {
            this["timeoutMs"] = 0;
        }
        if (!("axes" in $$source)) {
            this["axes"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MotionControllerProfile instance from a string or object.
     */
    static createFrom($$source: any = {}): MotionControllerProfile {
        const $$createField6_0 = $$createType34;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("axes" in $$parsedSource) {
            $$parsedSource["axes"] = $$createField6_0($$parsedSource["axes"]);
        }
        return new MotionControllerProfile($$parsedSource as Partial<MotionControllerProfile>);
    }
}

/**
 * MotionControllerStatus 运动控制器状态
 */
export class MotionControllerStatus {
    "id": string;
    "name": string;
    "type": MotionControllerType;
    "status": ConnectionStatus;
    "axes": AxisStatus[];
    "lastError": string;

    /** Creates a new MotionControllerStatus instance. */
    constructor($$source: Partial<MotionControllerStatus> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = MotionControllerType.$zero;
        }
        if (!("status" in $$source)) {
            this["status"] = ConnectionStatus.$zero;
        }
        if (!("axes" in $$source)) {
            this["axes"] = [];
        }
        if (!("lastError" in $$source)) {
            this["lastError"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MotionControllerStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): MotionControllerStatus {
        const $$createField4_0 = $$createType36;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("axes" in $$parsedSource) {
            $$parsedSource["axes"] = $$createField4_0($$parsedSource["axes"]);
        }
        return new MotionControllerStatus($$parsedSource as Partial<MotionControllerStatus>);
    }
}

/**
 * MotionControllerType 运动控制器类型
 */
export enum MotionControllerType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    MotionTypeSimulated = "SIMULATED-MC",
    MotionTypeB140 = "B140-MC",
};

/**
 * ProbeChannelConfig 探针通道配置
 */
export class ProbeChannelConfig {
    "name": string;
    "role": ProbeChannelRole;
    "channel": number;
    "enabled": boolean;

    /** Creates a new ProbeChannelConfig instance. */
    constructor($$source: Partial<ProbeChannelConfig> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("role" in $$source)) {
            this["role"] = ProbeChannelRole.$zero;
        }
        if (!("channel" in $$source)) {
            this["channel"] = 0;
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProbeChannelConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): ProbeChannelConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProbeChannelConfig($$parsedSource as Partial<ProbeChannelConfig>);
    }
}

/**
 * ProbeChannelRole 探针通道语义角色
 */
export enum ProbeChannelRole {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    RoleP1 = "fiveHole.p1",
    RoleP2 = "fiveHole.p2",
    RoleP3 = "fiveHole.p3",
    RoleP4 = "fiveHole.p4",
    RoleP5 = "fiveHole.p5",
    RolePAtm = "fiveHole.pAtm",
    RoleTAtm = "fiveHole.tAtm",
    RolePTotal = "fiveHole.pTotal",
};

/**
 * RectangleLayout 矩形布点配置
 */
export class RectangleLayout {
    "xMin": number;
    "xMax": number;
    "yMin": number;
    "yMax": number;
    "xSteps": StepSegment[];
    "ySteps": StepSegment[];

    /** Creates a new RectangleLayout instance. */
    constructor($$source: Partial<RectangleLayout> = {}) {
        if (!("xMin" in $$source)) {
            this["xMin"] = 0;
        }
        if (!("xMax" in $$source)) {
            this["xMax"] = 0;
        }
        if (!("yMin" in $$source)) {
            this["yMin"] = 0;
        }
        if (!("yMax" in $$source)) {
            this["yMax"] = 0;
        }
        if (!("xSteps" in $$source)) {
            this["xSteps"] = [];
        }
        if (!("ySteps" in $$source)) {
            this["ySteps"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RectangleLayout instance from a string or object.
     */
    static createFrom($$source: any = {}): RectangleLayout {
        const $$createField4_0 = $$createType32;
        const $$createField5_0 = $$createType32;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("xSteps" in $$parsedSource) {
            $$parsedSource["xSteps"] = $$createField4_0($$parsedSource["xSteps"]);
        }
        if ("ySteps" in $$parsedSource) {
            $$parsedSource["ySteps"] = $$createField5_0($$parsedSource["ySteps"]);
        }
        return new RectangleLayout($$parsedSource as Partial<RectangleLayout>);
    }
}

/**
 * SphereTankGateConfig 球罐门控配置
 */
export class SphereTankGateConfig {
    "enabled": boolean;
    "channelIndex": number;
    "thresholdRate": number;
    "stableTimeMs": number;

    /** Creates a new SphereTankGateConfig instance. */
    constructor($$source: Partial<SphereTankGateConfig> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("channelIndex" in $$source)) {
            this["channelIndex"] = 0;
        }
        if (!("thresholdRate" in $$source)) {
            this["thresholdRate"] = 0;
        }
        if (!("stableTimeMs" in $$source)) {
            this["stableTimeMs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SphereTankGateConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): SphereTankGateConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SphereTankGateConfig($$parsedSource as Partial<SphereTankGateConfig>);
    }
}

/**
 * StepSegment 分段步长区段
 */
export class StepSegment {
    "start": number;
    "end": number;
    "step": number;

    /** Creates a new StepSegment instance. */
    constructor($$source: Partial<StepSegment> = {}) {
        if (!("start" in $$source)) {
            this["start"] = 0;
        }
        if (!("end" in $$source)) {
            this["end"] = 0;
        }
        if (!("step" in $$source)) {
            this["step"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StepSegment instance from a string or object.
     */
    static createFrom($$source: any = {}): StepSegment {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StepSegment($$parsedSource as Partial<StepSegment>);
    }
}

/**
 * ThreeHoleCalibFileInfo 三孔校准文件信息
 */
export class ThreeHoleCalibFileInfo {
    "filePath": string;
    "fileName": string;

    /**
     * 校准马赫数
     */
    "cMa": number;

    /** Creates a new ThreeHoleCalibFileInfo instance. */
    constructor($$source: Partial<ThreeHoleCalibFileInfo> = {}) {
        if (!("filePath" in $$source)) {
            this["filePath"] = "";
        }
        if (!("fileName" in $$source)) {
            this["fileName"] = "";
        }
        if (!("cMa" in $$source)) {
            this["cMa"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ThreeHoleCalibFileInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ThreeHoleCalibFileInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ThreeHoleCalibFileInfo($$parsedSource as Partial<ThreeHoleCalibFileInfo>);
    }
}

/**
 * ThreeHoleChannelRole 三孔探针通道语义角色
 */
export enum ThreeHoleChannelRole {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * 1号孔压力
     */
    Role3H_P1 = "threeHole.p1",

    /**
     * 2号孔压力（中心孔）
     */
    Role3H_P2 = "threeHole.p2",

    /**
     * 3号孔压力
     */
    Role3H_P3 = "threeHole.p3",

    /**
     * 大气压
     */
    Role3H_PAtm = "threeHole.pAtm",

    /**
     * 大气温度
     */
    Role3H_TAtm = "threeHole.tAtm",
};

/**
 * ThreeHoleInterpolationResult 三孔插值结果
 */
export class ThreeHoleInterpolationResult {
    /**
     * 探针计算总压（表压 Pa）
     */
    "ptProbe": number;

    /**
     * 探针计算静压（表压 Pa）
     */
    "psProbe": number;

    /**
     * 计算马赫数
     */
    "machProbe": number;

    /**
     * 计算攻角（度）
     */
    "alphaProbe": number;

    /**
     * 计算速度（m/s）
     */
    "velocityProbe": number;

    /**
     * 迭代收敛次数
     */
    "iterationCount": number;

    /**
     * 迭代是否收敛
     */
    "converged": boolean;

    /**
     * 结果是否有效
     */
    "valid": boolean;

    /**
     * 无效/警告原因描述
     */
    "errorMsg"?: string;

    /** Creates a new ThreeHoleInterpolationResult instance. */
    constructor($$source: Partial<ThreeHoleInterpolationResult> = {}) {
        if (!("ptProbe" in $$source)) {
            this["ptProbe"] = 0;
        }
        if (!("psProbe" in $$source)) {
            this["psProbe"] = 0;
        }
        if (!("machProbe" in $$source)) {
            this["machProbe"] = 0;
        }
        if (!("alphaProbe" in $$source)) {
            this["alphaProbe"] = 0;
        }
        if (!("velocityProbe" in $$source)) {
            this["velocityProbe"] = 0;
        }
        if (!("iterationCount" in $$source)) {
            this["iterationCount"] = 0;
        }
        if (!("converged" in $$source)) {
            this["converged"] = false;
        }
        if (!("valid" in $$source)) {
            this["valid"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ThreeHoleInterpolationResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ThreeHoleInterpolationResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ThreeHoleInterpolationResult($$parsedSource as Partial<ThreeHoleInterpolationResult>);
    }
}

/**
 * ThreeHoleProbeChannelConfig 三孔探针通道配置
 */
export class ThreeHoleProbeChannelConfig {
    "name": string;
    "role": ThreeHoleChannelRole;
    "channel": number;
    "enabled": boolean;

    /** Creates a new ThreeHoleProbeChannelConfig instance. */
    constructor($$source: Partial<ThreeHoleProbeChannelConfig> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("role" in $$source)) {
            this["role"] = ThreeHoleChannelRole.$zero;
        }
        if (!("channel" in $$source)) {
            this["channel"] = 0;
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ThreeHoleProbeChannelConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): ThreeHoleProbeChannelConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ThreeHoleProbeChannelConfig($$parsedSource as Partial<ThreeHoleProbeChannelConfig>);
    }
}

/**
 * ThreeHoleRawData 三孔原始数据
 */
export class ThreeHoleRawData {
    "p1": number;
    "p2": number;
    "p3": number;
    "pAtm": number;
    "tAtm": number;

    /** Creates a new ThreeHoleRawData instance. */
    constructor($$source: Partial<ThreeHoleRawData> = {}) {
        if (!("p1" in $$source)) {
            this["p1"] = 0;
        }
        if (!("p2" in $$source)) {
            this["p2"] = 0;
        }
        if (!("p3" in $$source)) {
            this["p3"] = 0;
        }
        if (!("pAtm" in $$source)) {
            this["pAtm"] = 0;
        }
        if (!("tAtm" in $$source)) {
            this["tAtm"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ThreeHoleRawData instance from a string or object.
     */
    static createFrom($$source: any = {}): ThreeHoleRawData {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ThreeHoleRawData($$parsedSource as Partial<ThreeHoleRawData>);
    }
}

/**
 * ThreeHoleTraversalConfig 三孔移位测试配置
 */
export class ThreeHoleTraversalConfig {
    "name": string;

    /**
     * 采集设备ID
     */
    "deviceId": string;

    /**
     * 运动控制器ID
     */
    "motionControllerId": string;
    "layout": TraversalLayout;
    "probeChannels": ThreeHoleProbeChannelConfig[];
    "motionAlpha": MotionAxisMapping;
    "motionBeta": MotionAxisMapping;
    "calibFiles": ThreeHoleCalibFileInfo[];
    "dwellTimeMs": number;
    "samplesPerPoint": number;

    /**
     * 采样间隔（毫秒）
     */
    "sampleIntervalMs": number;

    /**
     * 运动等待超时（毫秒）
     */
    "motionTimeoutMs": number;
    "savePath": string;
    "saveFileName": string;

    /** Creates a new ThreeHoleTraversalConfig instance. */
    constructor($$source: Partial<ThreeHoleTraversalConfig> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("deviceId" in $$source)) {
            this["deviceId"] = "";
        }
        if (!("motionControllerId" in $$source)) {
            this["motionControllerId"] = "";
        }
        if (!("layout" in $$source)) {
            this["layout"] = (new TraversalLayout());
        }
        if (!("probeChannels" in $$source)) {
            this["probeChannels"] = [];
        }
        if (!("motionAlpha" in $$source)) {
            this["motionAlpha"] = (new MotionAxisMapping());
        }
        if (!("motionBeta" in $$source)) {
            this["motionBeta"] = (new MotionAxisMapping());
        }
        if (!("calibFiles" in $$source)) {
            this["calibFiles"] = [];
        }
        if (!("dwellTimeMs" in $$source)) {
            this["dwellTimeMs"] = 0;
        }
        if (!("samplesPerPoint" in $$source)) {
            this["samplesPerPoint"] = 0;
        }
        if (!("sampleIntervalMs" in $$source)) {
            this["sampleIntervalMs"] = 0;
        }
        if (!("motionTimeoutMs" in $$source)) {
            this["motionTimeoutMs"] = 0;
        }
        if (!("savePath" in $$source)) {
            this["savePath"] = "";
        }
        if (!("saveFileName" in $$source)) {
            this["saveFileName"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ThreeHoleTraversalConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): ThreeHoleTraversalConfig {
        const $$createField3_0 = $$createType24;
        const $$createField4_0 = $$createType38;
        const $$createField5_0 = $$createType39;
        const $$createField6_0 = $$createType39;
        const $$createField7_0 = $$createType41;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("layout" in $$parsedSource) {
            $$parsedSource["layout"] = $$createField3_0($$parsedSource["layout"]);
        }
        if ("probeChannels" in $$parsedSource) {
            $$parsedSource["probeChannels"] = $$createField4_0($$parsedSource["probeChannels"]);
        }
        if ("motionAlpha" in $$parsedSource) {
            $$parsedSource["motionAlpha"] = $$createField5_0($$parsedSource["motionAlpha"]);
        }
        if ("motionBeta" in $$parsedSource) {
            $$parsedSource["motionBeta"] = $$createField6_0($$parsedSource["motionBeta"]);
        }
        if ("calibFiles" in $$parsedSource) {
            $$parsedSource["calibFiles"] = $$createField7_0($$parsedSource["calibFiles"]);
        }
        return new ThreeHoleTraversalConfig($$parsedSource as Partial<ThreeHoleTraversalConfig>);
    }
}

/**
 * ThreeHoleTraversalDataPoint 三孔移位测试数据点
 */
export class ThreeHoleTraversalDataPoint {
    "pointId": string;
    "x": number;
    "y": number;
    "rawData": ThreeHoleRawData;
    "interpResult": ThreeHoleInterpolationResult;
    "sampleCount": number;
    "timestamp": number;

    /** Creates a new ThreeHoleTraversalDataPoint instance. */
    constructor($$source: Partial<ThreeHoleTraversalDataPoint> = {}) {
        if (!("pointId" in $$source)) {
            this["pointId"] = "";
        }
        if (!("x" in $$source)) {
            this["x"] = 0;
        }
        if (!("y" in $$source)) {
            this["y"] = 0;
        }
        if (!("rawData" in $$source)) {
            this["rawData"] = (new ThreeHoleRawData());
        }
        if (!("interpResult" in $$source)) {
            this["interpResult"] = (new ThreeHoleInterpolationResult());
        }
        if (!("sampleCount" in $$source)) {
            this["sampleCount"] = 0;
        }
        if (!("timestamp" in $$source)) {
            this["timestamp"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ThreeHoleTraversalDataPoint instance from a string or object.
     */
    static createFrom($$source: any = {}): ThreeHoleTraversalDataPoint {
        const $$createField3_0 = $$createType42;
        const $$createField4_0 = $$createType43;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("rawData" in $$parsedSource) {
            $$parsedSource["rawData"] = $$createField3_0($$parsedSource["rawData"]);
        }
        if ("interpResult" in $$parsedSource) {
            $$parsedSource["interpResult"] = $$createField4_0($$parsedSource["interpResult"]);
        }
        return new ThreeHoleTraversalDataPoint($$parsedSource as Partial<ThreeHoleTraversalDataPoint>);
    }
}

/**
 * ThreeHoleTraversalTaskStatus 三孔移位测试任务状态
 */
export class ThreeHoleTraversalTaskStatus {
    "taskId": string;
    "status": TraversalTestStatus;
    "totalPoints": number;
    "completedPoints": number;
    "progress": number;
    "currentPoint"?: TraversalPoint | null;
    "dataPoints": ThreeHoleTraversalDataPoint[];
    "lastError"?: string;

    /** Creates a new ThreeHoleTraversalTaskStatus instance. */
    constructor($$source: Partial<ThreeHoleTraversalTaskStatus> = {}) {
        if (!("taskId" in $$source)) {
            this["taskId"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = TraversalTestStatus.$zero;
        }
        if (!("totalPoints" in $$source)) {
            this["totalPoints"] = 0;
        }
        if (!("completedPoints" in $$source)) {
            this["completedPoints"] = 0;
        }
        if (!("progress" in $$source)) {
            this["progress"] = 0;
        }
        if (!("dataPoints" in $$source)) {
            this["dataPoints"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ThreeHoleTraversalTaskStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): ThreeHoleTraversalTaskStatus {
        const $$createField5_0 = $$createType28;
        const $$createField6_0 = $$createType45;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("currentPoint" in $$parsedSource) {
            $$parsedSource["currentPoint"] = $$createField5_0($$parsedSource["currentPoint"]);
        }
        if ("dataPoints" in $$parsedSource) {
            $$parsedSource["dataPoints"] = $$createField6_0($$parsedSource["dataPoints"]);
        }
        return new ThreeHoleTraversalTaskStatus($$parsedSource as Partial<ThreeHoleTraversalTaskStatus>);
    }
}

/**
 * TraversalLayout 布点配置
 */
export class TraversalLayout {
    "pattern": TraversalPattern;
    "line"?: LineLayout | null;
    "rectangle"?: RectangleLayout | null;
    "customPoints"?: TraversalPoint[];

    /** Creates a new TraversalLayout instance. */
    constructor($$source: Partial<TraversalLayout> = {}) {
        if (!("pattern" in $$source)) {
            this["pattern"] = TraversalPattern.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TraversalLayout instance from a string or object.
     */
    static createFrom($$source: any = {}): TraversalLayout {
        const $$createField1_0 = $$createType47;
        const $$createField2_0 = $$createType49;
        const $$createField3_0 = $$createType50;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("line" in $$parsedSource) {
            $$parsedSource["line"] = $$createField1_0($$parsedSource["line"]);
        }
        if ("rectangle" in $$parsedSource) {
            $$parsedSource["rectangle"] = $$createField2_0($$parsedSource["rectangle"]);
        }
        if ("customPoints" in $$parsedSource) {
            $$parsedSource["customPoints"] = $$createField3_0($$parsedSource["customPoints"]);
        }
        return new TraversalLayout($$parsedSource as Partial<TraversalLayout>);
    }
}

/**
 * TraversalPattern 布点模式
 */
export enum TraversalPattern {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    TraversalPatternLine = "line",
    TraversalPatternRectangle = "rectangle",
    TraversalPatternCustom = "custom",
};

/**
 * TraversalPoint 测试点位
 */
export class TraversalPoint {
    "id": string;
    "x": number;
    "y": number;

    /** Creates a new TraversalPoint instance. */
    constructor($$source: Partial<TraversalPoint> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("x" in $$source)) {
            this["x"] = 0;
        }
        if (!("y" in $$source)) {
            this["y"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TraversalPoint instance from a string or object.
     */
    static createFrom($$source: any = {}): TraversalPoint {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TraversalPoint($$parsedSource as Partial<TraversalPoint>);
    }
}

/**
 * TraversalTestStatus 测试状态
 */
export enum TraversalTestStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    TraversalStatusIdle = "idle",
    TraversalStatusRunning = "running",
    TraversalStatusPaused = "paused",
    TraversalStatusCompleted = "completed",
    TraversalStatusError = "error",
};

// Private type creation functions
const $$createType0 = EncoderCompensationConfig.createFrom;
const $$createType1 = ProbeChannelConfig.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = CalibrationPoint.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = SphereTankGateConfig.createFrom;
const $$createType6 = FiveHoleRawData.createFrom;
const $$createType7 = FiveHoleCoefficients.createFrom;
const $$createType8 = $Create.Nullable($$createType3);
const $$createType9 = CalibrationDataPoint.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = $Create.Array($Create.Any);
const $$createType12 = $Create.Array($Create.Any);
const $$createType13 = $Create.Array($Create.Any);
const $$createType14 = ChannelConfig.createFrom;
const $$createType15 = $Create.Array($$createType14);
const $$createType16 = FiveHoleProbeChannelConfig.createFrom;
const $$createType17 = $Create.Array($$createType16);
const $$createType18 = FiveHoleMotionAxisMapping.createFrom;
const $$createType19 = FiveHoleCalibFileInfo.createFrom;
const $$createType20 = $Create.Array($$createType19);
const $$createType21 = $Create.Nullable($$createType6);
const $$createType22 = FiveHoleInterpolationResult.createFrom;
const $$createType23 = $Create.Nullable($$createType22);
const $$createType24 = TraversalLayout.createFrom;
const $$createType25 = FiveHoleProbeConfig.createFrom;
const $$createType26 = $Create.Array($$createType25);
const $$createType27 = TraversalPoint.createFrom;
const $$createType28 = $Create.Nullable($$createType27);
const $$createType29 = FiveHoleProbeStatus.createFrom;
const $$createType30 = $Create.Array($$createType29);
const $$createType31 = StepSegment.createFrom;
const $$createType32 = $Create.Array($$createType31);
const $$createType33 = AxisConfig.createFrom;
const $$createType34 = $Create.Array($$createType33);
const $$createType35 = AxisStatus.createFrom;
const $$createType36 = $Create.Array($$createType35);
const $$createType37 = ThreeHoleProbeChannelConfig.createFrom;
const $$createType38 = $Create.Array($$createType37);
const $$createType39 = MotionAxisMapping.createFrom;
const $$createType40 = ThreeHoleCalibFileInfo.createFrom;
const $$createType41 = $Create.Array($$createType40);
const $$createType42 = ThreeHoleRawData.createFrom;
const $$createType43 = ThreeHoleInterpolationResult.createFrom;
const $$createType44 = ThreeHoleTraversalDataPoint.createFrom;
const $$createType45 = $Create.Array($$createType44);
const $$createType46 = LineLayout.createFrom;
const $$createType47 = $Create.Nullable($$createType46);
const $$createType48 = RectangleLayout.createFrom;
const $$createType49 = $Create.Nullable($$createType48);
const $$createType50 = $Create.Array($$createType27);
