// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDeviceProfile(arg1) {
  return window['go']['main']['App']['AddDeviceProfile'](arg1);
}

export function AddMotionProfile(arg1) {
  return window['go']['main']['App']['AddMotionProfile'](arg1);
}

export function ConnectDevice(arg1) {
  return window['go']['main']['App']['ConnectDevice'](arg1);
}

export function ConnectMotion(arg1) {
  return window['go']['main']['App']['ConnectMotion'](arg1);
}

export function DisconnectDevice(arg1) {
  return window['go']['main']['App']['DisconnectDevice'](arg1);
}

export function DisconnectMotion(arg1) {
  return window['go']['main']['App']['DisconnectMotion'](arg1);
}

export function ExportCalibrationPDF() {
  return window['go']['main']['App']['ExportCalibrationPDF']();
}

export function GetCalibrationStatus() {
  return window['go']['main']['App']['GetCalibrationStatus']();
}

export function GetDataDir() {
  return window['go']['main']['App']['GetDataDir']();
}

export function GetDeviceProfiles() {
  return window['go']['main']['App']['GetDeviceProfiles']();
}

export function GetDeviceStatusAll() {
  return window['go']['main']['App']['GetDeviceStatusAll']();
}

export function GetLatestData() {
  return window['go']['main']['App']['GetLatestData']();
}

export function GetMotionProfiles() {
  return window['go']['main']['App']['GetMotionProfiles']();
}

export function GetMotionStatusAll() {
  return window['go']['main']['App']['GetMotionStatusAll']();
}

export function GetPublishRate() {
  return window['go']['main']['App']['GetPublishRate']();
}

export function GetThreeHoleCalibInfo() {
  return window['go']['main']['App']['GetThreeHoleCalibInfo']();
}

export function GetThreeHoleTraversalStatus() {
  return window['go']['main']['App']['GetThreeHoleTraversalStatus']();
}

export function IsRecording() {
  return window['go']['main']['App']['IsRecording']();
}

export function IsThreeHoleCalibLoaded() {
  return window['go']['main']['App']['IsThreeHoleCalibLoaded']();
}

export function ListRecordingFiles() {
  return window['go']['main']['App']['ListRecordingFiles']();
}

export function LoadCSVFile() {
  return window['go']['main']['App']['LoadCSVFile']();
}

export function LoadThreeHoleCalibFiles(arg1) {
  return window['go']['main']['App']['LoadThreeHoleCalibFiles'](arg1);
}

export function LoadThreeHoleConfig() {
  return window['go']['main']['App']['LoadThreeHoleConfig']();
}

export function MotionDefinePosition(arg1, arg2, arg3) {
  return window['go']['main']['App']['MotionDefinePosition'](arg1, arg2, arg3);
}

export function MotionEmergencyStop(arg1) {
  return window['go']['main']['App']['MotionEmergencyStop'](arg1);
}

export function MotionGetLimitStatus(arg1, arg2) {
  return window['go']['main']['App']['MotionGetLimitStatus'](arg1, arg2);
}

export function MotionHome(arg1, arg2) {
  return window['go']['main']['App']['MotionHome'](arg1, arg2);
}

export function MotionIsAxisMoving(arg1, arg2) {
  return window['go']['main']['App']['MotionIsAxisMoving'](arg1, arg2);
}

export function MotionIsMoving(arg1) {
  return window['go']['main']['App']['MotionIsMoving'](arg1);
}

export function MotionJog(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['MotionJog'](arg1, arg2, arg3, arg4);
}

export function MotionMotorOff(arg1) {
  return window['go']['main']['App']['MotionMotorOff'](arg1);
}

export function MotionMoveBy(arg1, arg2, arg3) {
  return window['go']['main']['App']['MotionMoveBy'](arg1, arg2, arg3);
}

export function MotionMoveTo(arg1, arg2, arg3) {
  return window['go']['main']['App']['MotionMoveTo'](arg1, arg2, arg3);
}

export function MotionSetAcceleration(arg1, arg2, arg3) {
  return window['go']['main']['App']['MotionSetAcceleration'](arg1, arg2, arg3);
}

export function MotionSetAxisDirection(arg1, arg2, arg3) {
  return window['go']['main']['App']['MotionSetAxisDirection'](arg1, arg2, arg3);
}

export function MotionSetDeceleration(arg1, arg2, arg3) {
  return window['go']['main']['App']['MotionSetDeceleration'](arg1, arg2, arg3);
}

export function MotionStop(arg1, arg2) {
  return window['go']['main']['App']['MotionStop'](arg1, arg2);
}

export function MotionWaitForComplete(arg1, arg2, arg3) {
  return window['go']['main']['App']['MotionWaitForComplete'](arg1, arg2, arg3);
}

export function PauseCalibration() {
  return window['go']['main']['App']['PauseCalibration']();
}

export function PauseThreeHoleTraversal() {
  return window['go']['main']['App']['PauseThreeHoleTraversal']();
}

export function ReadRecordingFile(arg1) {
  return window['go']['main']['App']['ReadRecordingFile'](arg1);
}

export function RemoveDeviceProfile(arg1) {
  return window['go']['main']['App']['RemoveDeviceProfile'](arg1);
}

export function RemoveMotionProfile(arg1) {
  return window['go']['main']['App']['RemoveMotionProfile'](arg1);
}

export function ResumeCalibration() {
  return window['go']['main']['App']['ResumeCalibration']();
}

export function ResumeThreeHoleTraversal() {
  return window['go']['main']['App']['ResumeThreeHoleTraversal']();
}

export function SaveThreeHoleConfig(arg1) {
  return window['go']['main']['App']['SaveThreeHoleConfig'](arg1);
}

export function ScanDevices() {
  return window['go']['main']['App']['ScanDevices']();
}

export function SelectDataSavePath() {
  return window['go']['main']['App']['SelectDataSavePath']();
}

export function SelectThreeHoleCalibFiles() {
  return window['go']['main']['App']['SelectThreeHoleCalibFiles']();
}

export function SetDataSavePath(arg1) {
  return window['go']['main']['App']['SetDataSavePath'](arg1);
}

export function SetPublishRate(arg1) {
  return window['go']['main']['App']['SetPublishRate'](arg1);
}

export function StartAcquisition(arg1) {
  return window['go']['main']['App']['StartAcquisition'](arg1);
}

export function StartAcquisitionAll() {
  return window['go']['main']['App']['StartAcquisitionAll']();
}

export function StartCalibration(arg1) {
  return window['go']['main']['App']['StartCalibration'](arg1);
}

export function StartRecording() {
  return window['go']['main']['App']['StartRecording']();
}

export function StartThreeHoleRealtimeMonitor(arg1) {
  return window['go']['main']['App']['StartThreeHoleRealtimeMonitor'](arg1);
}

export function StartThreeHoleTraversal(arg1) {
  return window['go']['main']['App']['StartThreeHoleTraversal'](arg1);
}

export function StopAcquisition(arg1) {
  return window['go']['main']['App']['StopAcquisition'](arg1);
}

export function StopAcquisitionAll() {
  return window['go']['main']['App']['StopAcquisitionAll']();
}

export function StopCalibration() {
  return window['go']['main']['App']['StopCalibration']();
}

export function StopRecording() {
  return window['go']['main']['App']['StopRecording']();
}

export function StopThreeHoleRealtimeMonitor() {
  return window['go']['main']['App']['StopThreeHoleRealtimeMonitor']();
}

export function StopThreeHoleTraversal() {
  return window['go']['main']['App']['StopThreeHoleTraversal']();
}

export function UpdateDeviceProfile(arg1) {
  return window['go']['main']['App']['UpdateDeviceProfile'](arg1);
}

export function UpdateMotionProfile(arg1) {
  return window['go']['main']['App']['UpdateMotionProfile'](arg1);
}
